// Auto-generated by `supabase gen types typescript`
// Run: npx supabase gen types typescript --local > lib/supabase/types.ts
// Placeholder until migration is applied
export type Database = {
  public: {
    Tables: Record<string, unknown>
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
    Enums: Record<string, unknown>
  }
}
